INSERT INTO ASSOCIADO (NOME) VALUES ('Gabriel');
INSERT INTO ASSOCIADO (NOME) VALUES ('Joao');
INSERT INTO ASSOCIADO (NOME) VALUES ('Maria');

INSERT INTO PAUTA (DESCRICAO) VALUES ('Pauta Teste');
 

